---
title: "Figure S11: Characterization of BE cells"
author: "Karol Nowicki-Osuch, based on Nils Eling's code"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script plots cell-types of BE and highlights marker genes.

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(DropletUtils)
library(openxlsx)
library(Rtsne)
library(pheatmap)
library(viridis)
library(umap)
source("../../Analysis/Functions/auxiliary.R")

sce <- readRDS("~/Dropbox/Postdoc/2019-12-29_BE2020/All_corrected_sce_filtered.rds")

# Remove contaminating cell-types
sce <- sce[,sce$include]
```

# Barret's oesophagus

We will visualize marker genes of Barret's oesophagus.

## Dimensionality reduction

```{r}
cur_sce <- sce[,sce$Tissue == "BE"]

# Only genes that are expressed
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]

# Normalization across all cells
cur_sce <- computeSumFactors(cur_sce, clusters=paste(cur_sce$cell_type_secondary))
cur_sce <- logNormCounts(cur_sce, log = TRUE)


# Split the samples to perform batch correction
sce.list <- split.sce(cur_sce, unique(cur_sce$Sample), colData.name = "Sample")
# Order sce object by size
sce.list <- sce.list[order(unlist(lapply(sce.list, ncol)), decreasing = TRUE)]

cur_sce <- do.call("cbind", sce.list)
corrected <- batch.correction(sce.list)

# Compute tSNE
set.seed(12345)
tsne <- Rtsne(t(corrected), pca = FALSE, perplexity = 100)
umap <- umap(t(corrected))

# Create colour vector
colour_vector <- vector(length = length(unique(cur_sce$cell_type_secondary)))
names(colour_vector) <- unique(cur_sce$cell_type_secondary)
colour_vector["Immune_T-cells"] <- "grey20"
colour_vector["Immune_B-cells"] <- "grey30"
colour_vector["Immune_Macrophages"] <- "grey40"
colour_vector["Stromal_CALD1_cells"] <- "grey60"
colour_vector["Stromal_GNG11_cells"] <- "grey70"

colour_vector["Columnar_Undifferentiated"] <- "white"
colour_vector["Columnar_Undifferentiated_Dividing"] <- colorRampPalette(c("white", "#00A087FF"))(10)[2]
colour_vector["Columnar_Intermediate"] <- colorRampPalette(c("white", "#00A087FF"))(10)[4]
colour_vector["Columnar_differentiated"] <- colorRampPalette(c("white", "#00A087FF"))(10)[6]
colour_vector["Endocrine_NEUROG3"] <- colorRampPalette(c("white", "dark green"))(10)[5]
colour_vector["Goblet"] <- colorRampPalette(c("white", "dark green"))(10)[10]


tsne.BE <- ggplot(data.frame(tSNE1 = tsne$Y[,1],
                  tSNE2 = tsne$Y[,2],
                  cell_type = cur_sce$cell_type_secondary)) + 
  geom_point(aes(tSNE1, tSNE2), colour = "black", size = 2) +
  geom_point(aes(tSNE1, tSNE2, colour = cell_type)) +
  theme_minimal()+
  scale_color_manual(values = colour_vector)
tsne.BE

umap.BE <- ggplot(data.frame(UMAP1 = umap$layout[,1],
                  UMAP2 = umap$layout[,2],
                  cell_type = cur_sce$cell_type_secondary)) + 
  geom_point(aes(UMAP1, UMAP2), colour = "black", size = 2) +
  geom_point(aes(UMAP1, UMAP2, colour = cell_type)) +
  theme_minimal()+
  scale_color_manual(values = colour_vector)
umap.BE

ggplot(data.frame(tSNE1 = tsne$Y[,1],
                  tSNE2 = tsne$Y[,2],
                  cell_type = as.factor(cur_sce$Tissue_cluster))) + 
  geom_point(aes(tSNE1, tSNE2), colour = "black", size = 2) +
  geom_point(aes(tSNE1, tSNE2, colour = cell_type)) +
  theme_minimal()

ggsave("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Supplementary_figures/S11/BE_umap.pdf", umap.BE, width = 9, height = 5, useDingbats = FALSE)

ggsave("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Supplementary_figures/S11/BE_tsne.pdf", tsne.BE, width = 9, height = 5, useDingbats = FALSE)
```

```{r}
# Remove non-expressed genes
cur_sce <- cur_sce[Matrix::rowSums(counts(cur_sce)) > 0,]

# Perform DE to find marker genes
DE.genes <- multi.DE(sce = cur_sce, 
                     conditions = cur_sce$cell_type_secondary,
                     covariate = cur_sce$Patient,
                     lfc = 0.5,
                     FDR = 0.1)

# Save as table
write.xlsx(DE.genes, file = "~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Supplemental_tables/Table_S7.xlsx")
```

## Marker gene expression

Here, we visualize marker gene expression in form of a heatmap

```{r}
genes <- c("PTPRC", "VIM", 
           "MUC5AC", "KRT20", 
           "MUC6", 
           "MUC2", "TFF3", "KRT7",
           "CHGA", "NEUROG3", 
           "OLFM4")

# Normalization across all cells
cur_sce <- computeSumFactors(cur_sce, clusters=paste(cur_sce$cell_type_secondary))
cur_sce <- logNormCounts(cur_sce, log = TRUE)

for.heatmap <- logcounts(cur_sce)[match(genes, rowData(cur_sce)$Symbol),]
colnames(for.heatmap) <- paste(cur_sce$Barcode, cur_sce$Patient, sep = "_")

# Order cells by cell-type
ordering <- c(which(cur_sce$cell_type_secondary == "Stromal_CALD1_cells"),
              which(cur_sce$cell_type_secondary == "Stromal_GNG11_cells"),
              which(cur_sce$cell_type_secondary == "Immune_T-cells"),
              which(cur_sce$cell_type_secondary == "Immune_B-cells"),
              which(cur_sce$cell_type_secondary == "Immune_Macrophages"),
              which(cur_sce$cell_type_secondary == "Columnar_Undifferentiated"),
              which(cur_sce$cell_type_secondary == "Columnar_Undifferentiated_Dividing"),
               which(cur_sce$cell_type_secondary == "Columnar_Intermediate"),
               which(cur_sce$cell_type_secondary == "Columnar_differentiated"),
               which(cur_sce$cell_type_secondary == "Endocrine_NEUROG3"),
               which(cur_sce$cell_type_secondary == "Goblet"))

dev.off()
pdf(file = "~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Supplementary_figures/S11/BE_heatmap.pdf", height = 7, width = 7, useDingbats = FALSE)
pheatmap(for.heatmap[,ordering], cluster_rows = FALSE, color = viridis(100), 
         labels_row = genes, show_colnames = FALSE,
         annotation_col = data.frame(row.names = colnames(for.heatmap)[ordering],
                                     cell_type = cur_sce$cell_type_secondary[ordering]), 
         annotation_colors = list(cell_type = colour_vector),
         cluster_cols = FALSE)
dev.off()
```

# End Matter

To finish get session info:

```{r Endnote, include=TRUE, echo=TRUE, warning=FALSE, eval=TRUE, message=FALSE, tidy=TRUE}
sessionInfo()
```
