---
title: "Data visualisation of Battenberg analysis"
author: "Karol Nowicki-Osuch"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

Load libraries and prepare ploting functions

```{r libraries, message=FALSE}
# library(DPClust)
library(matrixStats)
library(RColorBrewer)
library(ggplot2)

# This function will plot clusters and colours and density plots. Adapted from DPClust
plotnD_new <- function(xvals, yvals, zvals, subclonal.fraction_x, subclonal.fraction_y, samplename_x, 
                       samplename_y, max.plotted.value=NA, cluster.locations=NULL, plot_mutations=F, 
                       plot_mutations_colour=NULL, cex = 1, title = NA) {
  colours=colorRampPalette(c("white","red"))
  
  # Determine the minimum and maximum plotted values
  if (!is.na(max.plotted.value)) {
    range=list(c(-0.1,max.plotted.value), c(-0.1,max.plotted.value))
    # Subset x,y,z to remove data outside the plot
    zvals = data.matrix(zvals[xvals<=max.plotted.value,yvals<=max.plotted.value])
    xvals = data.matrix(xvals[xvals<=max.plotted.value])
    yvals = data.matrix(yvals[yvals<=max.plotted.value])
  } else {
    # Set dynamic range based on the subclonal fraction data
    range=list(c(floor(min(subclonal.fraction_x)*10)-1,ceiling(max(subclonal.fraction_x)*10)+1)/10, 
               c(floor(min(subclonal.fraction_y)*10)-1,ceiling(max(subclonal.fraction_y)*10)+1)/10)
  }
  
  #plot.data = cbind(data[[i]]$subclonal.fraction,data[[j]]$subclonal.fraction)
  plot.data = cbind(subclonal.fraction_x, subclonal.fraction_y)
  if(!is.na(max.plotted.value)) {
    plot_mutations_colour = plot_mutations_colour[plot.data[,1]<=max.plotted.value & plot.data[,2]<=max.plotted.value]
    plot.data = plot.data[plot.data[,1]<=max.plotted.value & plot.data[,2]<=max.plotted.value,]
  }
  
  if (!is.null(cluster.locations) & !plot_mutations) {
    # Plot the cluster locations on top of the density
    panel_function = function(...) { 
      lattice::panel.levelplot(...)
      lattice::panel.abline(h = 0:ceiling(max(plot.data)))
      lattice::panel.abline(v = 0:ceiling(max(plot.data)))
      lattice::lpoints(cluster.locations, pch=".", cex=cex, col="black", )
    }
  } else if (plot_mutations & is.null(plot_mutations_colour)) {
    # Plot the mutations overlayed on top of the density
    panel_function = function(...) { 
      lattice::panel.levelplot(...)
      lattice::panel.abline(h = 0:ceiling(max(plot.data)))
      lattice::panel.abline(v = 0:ceiling(max(plot.data)))     
      lattice::panel.segments(x0 = 0.5, y0 = 0.5, y1 = 10, x1 = 0.5, col = "red")
      lattice::panel.segments(x0 = 0.5, y0 = 0.5, y1 = 0.5 , x1 = 10, col = "red")
      lattice::lpoints(plot.data, pch=16, cex=cex, col="black") 
    }
  } else if (plot_mutations & !is.null(plot_mutations_colour)) {
    # Plot the mutations overlayed on top of the density and add custom colours
    panel_function = function(...) { 
      lattice::panel.levelplot(...)
      lattice::panel.abline(h = 0:ceiling(max(plot.data)))
      lattice::panel.abline(v = 0:ceiling(max(plot.data)))
      lattice::panel.segments(x0 = 0.5, y0 = 0.5, y1 = 10, x1 = 0.5, col = "red")
      lattice::panel.segments(x0 = 0.5, y0 = 0.5, y1 = 0.5 , x1 = 10, col = "red")
      lattice::lpoints(plot.data, pch=16, cex=cex, col=plot_mutations_colour)
      
      
    }
    
  } else {
    # No overlay to be plotted
    panel_function = function(...) { 
      lattice::panel.levelplot(...)
      lattice::panel.abline(h = 0:ceiling(max(plot.data)))
      lattice::panel.abline(v = 0:ceiling(max(plot.data)))
    }
  }
  
  if (is.null(plot_mutations_colour)) {
    fig = lattice::levelplot(zvals,
                             row.values=xvals,
                             column.values=yvals,
                             xlim=range[[1]],
                             ylim=range[[2]],
                             xlab=list(label=samplename_x,cex=2),
                             ylab=list(label=samplename_y,cex=2),
                             scales=list(x=list(cex=1.25),y=list(cex=1.25)),
                             col.regions=colours,
                             main=title,
                             colorkey=F,
                             panel=panel_function,  
                             
    )  
  } else {
    fig = lattice::levelplot(zvals,
                             row.values=xvals,
                             column.values=yvals,
                             xlim=range[[1]],
                             ylim=range[[2]],
                             xlab=list(label=samplename_x,cex=2),
                             ylab=list(label=samplename_y,cex=2),
                             scales=list(x=list(cex=1.25),y=list(cex=1.25)),
                             col.regions=colours,
                             main=title,
                             colorkey=F,
                             panel=panel_function, 
                             key=list(space="right",
                                      title = "Cluster",
                                      points=list(col=colour.palet, pch = 16, cex=cex),
                                      text=list(names(colour.palet))
                                      
                             )
    )
  }                        
  
  print(fig)
  
}


# Plot scatter with histograms of data attached on the sides
scatterhist <- function(x, y, xhist, yhist, xlab="", ylab="", main = "", plot_mutations_colour=NULL, max.plotted.value=c(1,1), cutoff = NULL) {
  zones=matrix(c(2,0,1,3), ncol=2, byrow=TRUE)
  layout(zones, widths=c(4/5,1/5), heights=c(1/5,4/5))
  xhist = hist(xhist[xhist>0 & xhist < max.plotted.value[1]], plot=FALSE, breaks = seq(-0.00, max.plotted.value[1], by = 0.01), include.lowest = TRUE)
  yhist = hist(yhist[yhist>0 & yhist < max.plotted.value[2]], plot=FALSE, breaks = seq(-0.00, max.plotted.value[2], by = 0.01), include.lowest = TRUE)
  par(mar=c(3,3,1,1))
  plot(x,y, xlim=c(0,max.plotted.value[1]), ylim=c(0,max.plotted.value[2]), pch = 19, col = plot_mutations_colour)
  abline(v=cutoff, col="red")
  par(mar=c(0,3,1,1), adj = 0.6)
  barplot(xhist$counts, axes=FALSE, space=0, main = main)
  par(mar=c(3,0,1,1))
  barplot(yhist$counts, axes=FALSE, space=0, horiz=TRUE)
  par(oma=c(3,3,0,0))
  mtext(xlab, side=1, line=1, outer=TRUE, adj=0, at = 0.4)
  mtext(ylab, side=2, line=1, outer=TRUE, adj=0, at = 0.4) 
  layout(matrix(1,1))
}


sample.names<-c("NE", "NG", "BE")
samples <- read.delim("/home/karolno/Dropbox/Postdoc/git/BE_WGS/Samples", stringsAsFactors = FALSE)
data.location <- "/mnt/data/Karol/BE_origin/Newest/DPClust_final/"
count.cutoff=2 # must be equal or bigger than that in at least one sample
z.cutoff=30 # Must be bigger than that in all samples
```

# AHM0062

For each speciment the following steps are undertaken:

* Load BE data from DPClust analysis
* Identify clonal clusters in BE
* Plot clusters in BE samples
* Load multisample DPClust data
* Plot figures only with BE clonal mutations 


```{r AHM0062}
sample<-"AHM0062"
par(oma=c(3,3,0,0))
layout(matrix(1,1))

# ID of samples
samples.IDs<-samples[samples$Patient == sample & samples$Tissue %in% c("NE", "GC", "BE"),]
samples.IDs<-samples.IDs$Pool[match(samples.IDs$Tissue, c("NE", "GC", "BE"))]

# Read in data for DPCLust analysis of BE sample (by itself)
if (dir.exists(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/"))) {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
} else {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
}

# Identify clonal clusters
BE.clonal<- clustering$best.node.assignments %in% which(clustering$cluster.locations[,2]>0.8)

# Get tracking ID
tracking <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Store cluster information for BE sampels 
BE.cluster <-  clustering$best.node.assignments 

# Load data for multisamples DPClust analysis
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample, "_gsdata.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))

# Create colour palet that will be constant on all images
colour.palet<-c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 8, name = "Set2"))[1:max(clustering$cluster.locations[,1])]
names(colour.palet) <- clustering$cluster.locations[,1]

# Get tracking ID for the multisample DPClust
tracking2 <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Check if the mutations fulfils coverage test
cov.test <- rowAlls(dataset$WTCount+dataset$mutCount > z.cutoff)

# Check if the mutation is supported by enough reads
count.test <- rowAnys(dataset$mutCount > count.cutoff)

# Select data and build data printing dataframe
dataset$chromosome <- dataset$chromosome[cov.test & count.test,]
dataset$position <- dataset$position[cov.test & count.test,]
dataset$WTCount <- dataset$WTCount[cov.test & count.test,]
dataset$mutCount <- dataset$mutCount[cov.test & count.test,]
dataset$subclonal.fraction <- dataset$subclonal.fraction[cov.test & count.test,]
clustering$best.node.assignments <- clustering$best.node.assignments[cov.test & count.test]

BE.clonal <- BE.clonal[tracking %in% tracking2][cov.test & count.test]
BE.cluster <- BE.cluster[tracking %in% tracking2][cov.test & count.test]
# BE.clonal<-BE.clonal[cov.test & count.test]
# BE.clonal<- dataset$subclonal.fraction[,3]>0.5 

# Get vaf data
vaf.data <- dataset$mutCount/(dataset$mutCount+dataset$WTCount)


data.plot<-data.frame( "chr" = dataset$chromosome[ ,1 , drop = FALSE],
                       "position" = dataset$position[ ,1 , drop = FALSE],
                       "WTCount" = as.numeric(dataset$WTCount[ ,3 , drop = FALSE]),
                       "mutCount" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]),
                       "vaf" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]/(dataset$mutCount[ ,3 , drop = FALSE]+dataset$WTCount[ ,3 , drop = FALSE])),
                       "subfrac" = as.numeric(dataset$subclonal.fraction[ ,3 , drop = FALSE]),
                       "Cluster" = factor(BE.cluster)
)

rownames(data.plot)<-paste0("chr", data.plot$chr,":",data.plot$position)


# Check if mutations is prsent in all samples
is.all<-rowAlls(dataset$mutCount > count.cutoff)
# Check if mutations is present in normal samples
is.both<-rowAlls(dataset$mutCount[,1:2] > count.cutoff)

# Identify the mutations that are clonal in BE and approproprioate number of reads supporting the mutations and are missing in the normal smaples
is.BE<-data.plot$mutCount >= count.cutoff & BE.clonal & !is.both & data.plot$vaf > 0.15

# Plot only data for the BE samples from 1 samples DPClust

BE.only<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = Cluster, fill = Cluster)) + geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity")+ theme_minimal()+scale_color_manual(values = colour.palet) + scale_fill_manual(values = colour.palet) + ggtitle(paste("BE", sample)) + theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + ylab("Number of mutations") + xlab("% BE cells") + xlim(0,2.1)
BE.only
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only.pdf"), BE.only, width = 14, height = 5, useDingbats = FALSE)

BE.clonal<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = as.factor(is.BE[data.plot$mutCount>0]), fill = as.factor(is.BE[data.plot$mutCount>0]))) + 
  geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + 
  geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity") +
  theme_minimal() + 
  scale_color_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE), values = c("FALSE" = "red", "TRUE" = "black")) + 
  scale_fill_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE),values = c("FALSE" = "red", "TRUE" = "black")) + 
  ggtitle(paste("BE", sample)) + 
  theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + 
  ylab("Number of mutations") + 
  xlab("% BE cells") + 
  xlim(0,2.1)
BE.clonal
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only_bw.pdf"), BE.clonal, width = 14, height = 5, useDingbats = FALSE)

i<-1
j<-3
# Plot the expression of these in BE and NE comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NE.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.6)
dev.off()

i<-2
j<-3
# Plot the expression of these in BE and NG comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NG.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.5)
dev.off()
```

# AHM0231

```{r AHM0231}
sample<-"AHM0231"
par(oma=c(3,3,0,0))
layout(matrix(1,1))

# ID of samples
samples.IDs<-samples[samples$Patient == sample & samples$Tissue %in% c("NE", "GC", "BE"),]
samples.IDs<-samples.IDs$Pool[match(samples.IDs$Tissue, c("NE", "GC", "BE"))]

# Read in data for DPCLust analysis of BE sample (by itself)
if (dir.exists(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/"))) {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
} else {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
}

# Identify clonal clusters
BE.clonal<- clustering$best.node.assignments %in% which(clustering$cluster.locations[,2]>0.8)

# Get tracking ID
tracking <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Store cluster information for BE sampels 
BE.cluster <-  clustering$best.node.assignments 

# Load data for multisamples DPClust analysis
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample, "_gsdata.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))

# Create colour palet that will be constant on all images
colour.palet<-c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 8, name = "Set2"))[1:max(clustering$cluster.locations[,1])]
names(colour.palet) <- clustering$cluster.locations[,1]

# Get tracking ID for the multisample DPClust
tracking2 <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Check if the mutations fulfils coverage test
cov.test <- rowAlls(dataset$WTCount+dataset$mutCount > z.cutoff)

# Check if the mutation is supported by enough reads
count.test <- rowAnys(dataset$mutCount > count.cutoff)

# Select data and build data printing dataframe
dataset$chromosome <- dataset$chromosome[cov.test & count.test,]
dataset$position <- dataset$position[cov.test & count.test,]
dataset$WTCount <- dataset$WTCount[cov.test & count.test,]
dataset$mutCount <- dataset$mutCount[cov.test & count.test,]
dataset$subclonal.fraction <- dataset$subclonal.fraction[cov.test & count.test,]
clustering$best.node.assignments <- clustering$best.node.assignments[cov.test & count.test]

BE.clonal <- BE.clonal[tracking %in% tracking2][cov.test & count.test]
BE.cluster <- BE.cluster[tracking %in% tracking2][cov.test & count.test]
# BE.clonal<-BE.clonal[cov.test & count.test]
# BE.clonal<- dataset$subclonal.fraction[,3]>0.5 

# Get vaf data
vaf.data <- dataset$mutCount/(dataset$mutCount+dataset$WTCount)


data.plot<-data.frame( "chr" = dataset$chromosome[ ,1 , drop = FALSE],
                       "position" = dataset$position[ ,1 , drop = FALSE],
                       "WTCount" = as.numeric(dataset$WTCount[ ,3 , drop = FALSE]),
                       "mutCount" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]),
                       "vaf" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]/(dataset$mutCount[ ,3 , drop = FALSE]+dataset$WTCount[ ,3 , drop = FALSE])),
                       "subfrac" = as.numeric(dataset$subclonal.fraction[ ,3 , drop = FALSE]),
                       "Cluster" = factor(BE.cluster)
)

rownames(data.plot)<-paste0("chr", data.plot$chr,":",data.plot$position)


# Check if mutations is prsent in all samples
is.all<-rowAlls(dataset$mutCount > count.cutoff)
# Check if mutations is present in normal samples
is.both<-rowAlls(dataset$mutCount[,1:2] > count.cutoff)

# Identify the mutations that are clonal in BE and approproprioate number of reads supporting the mutations and are missing in the normal smaples
is.BE<-data.plot$mutCount >= count.cutoff & BE.clonal & !is.both & data.plot$vaf > 0.15

# Plot only data for the BE samples from 1 samples DPClust

BE.only<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = Cluster, fill = Cluster)) + geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity")+ theme_minimal()+scale_color_manual(values = colour.palet) + scale_fill_manual(values = colour.palet) + ggtitle(paste("BE", sample)) + theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + ylab("Number of mutations") + xlab("% BE cells") + xlim(0,2.1)
BE.only
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only.pdf"), BE.only, width = 14, height = 5, useDingbats = FALSE)

BE.clonal<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = as.factor(is.BE[data.plot$mutCount>0]), fill = as.factor(is.BE[data.plot$mutCount>0]))) + 
  geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + 
  geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity") +
  theme_minimal() + 
  scale_color_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE), values = c("FALSE" = "red", "TRUE" = "black")) + 
  scale_fill_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE),values = c("FALSE" = "red", "TRUE" = "black")) + 
  ggtitle(paste("BE", sample)) + 
  theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + 
  ylab("Number of mutations") + 
  xlab("% BE cells") + 
  xlim(0,2.1)
BE.clonal
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only_bw.pdf"), BE.clonal, width = 14, height = 5, useDingbats = FALSE)

i<-1
j<-3
# Plot the expression of these in BE and NE comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NE.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.6)
dev.off()

i<-2
j<-3
# Plot the expression of these in BE and NG comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NG.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.5)
dev.off()
```

# AHM0848

```{r AHM0848}
sample<-"AHM0848"
par(oma=c(3,3,0,0))
layout(matrix(1,1))

# ID of samples
samples.IDs<-samples[samples$Patient == sample & samples$Tissue %in% c("NE", "GC", "BE"),]
samples.IDs<-samples.IDs$Pool[match(samples.IDs$Tissue, c("NE", "GC", "BE"))]

# Read in data for DPCLust analysis of BE sample (by itself)
if (dir.exists(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/"))) {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
} else {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
}

# Identify clonal clusters
BE.clonal<- clustering$best.node.assignments %in% which(clustering$cluster.locations[,2]>0.8)

# Get tracking ID
tracking <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Store cluster information for BE sampels 
BE.cluster <-  clustering$best.node.assignments 

# Load data for multisamples DPClust analysis
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample, "_gsdata.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))

# Create colour palet that will be constant on all images
colour.palet<-c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 8, name = "Set2"))[1:max(clustering$cluster.locations[,1])]
names(colour.palet) <- clustering$cluster.locations[,1]

# Get tracking ID for the multisample DPClust
tracking2 <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Check if the mutations fulfils coverage test
cov.test <- rowAlls(dataset$WTCount+dataset$mutCount > z.cutoff)

# Check if the mutation is supported by enough reads
count.test <- rowAnys(dataset$mutCount > count.cutoff)

# Select data and build data printing dataframe
dataset$chromosome <- dataset$chromosome[cov.test & count.test,]
dataset$position <- dataset$position[cov.test & count.test,]
dataset$WTCount <- dataset$WTCount[cov.test & count.test,]
dataset$mutCount <- dataset$mutCount[cov.test & count.test,]
dataset$subclonal.fraction <- dataset$subclonal.fraction[cov.test & count.test,]
clustering$best.node.assignments <- clustering$best.node.assignments[cov.test & count.test]

BE.clonal <- BE.clonal[tracking %in% tracking2][cov.test & count.test]
BE.cluster <- BE.cluster[tracking %in% tracking2][cov.test & count.test]
# BE.clonal<-BE.clonal[cov.test & count.test]
# BE.clonal<- dataset$subclonal.fraction[,3]>0.5 

# Get vaf data
vaf.data <- dataset$mutCount/(dataset$mutCount+dataset$WTCount)


data.plot<-data.frame( "chr" = dataset$chromosome[ ,1 , drop = FALSE],
                       "position" = dataset$position[ ,1 , drop = FALSE],
                       "WTCount" = as.numeric(dataset$WTCount[ ,3 , drop = FALSE]),
                       "mutCount" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]),
                       "vaf" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]/(dataset$mutCount[ ,3 , drop = FALSE]+dataset$WTCount[ ,3 , drop = FALSE])),
                       "subfrac" = as.numeric(dataset$subclonal.fraction[ ,3 , drop = FALSE]),
                       "Cluster" = factor(BE.cluster)
)

rownames(data.plot)<-paste0("chr", data.plot$chr,":",data.plot$position)


# Check if mutations is prsent in all samples
is.all<-rowAlls(dataset$mutCount > count.cutoff)
# Check if mutations is present in normal samples
is.both<-rowAlls(dataset$mutCount[,1:2] > count.cutoff)

# Identify the mutations that are clonal in BE and approproprioate number of reads supporting the mutations and are missing in the normal smaples
is.BE<-data.plot$mutCount >= count.cutoff & BE.clonal & !is.both & data.plot$vaf > 0.15

# Plot only data for the BE samples from 1 samples DPClust

BE.only<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = Cluster, fill = Cluster)) + geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity")+ theme_minimal()+scale_color_manual(values = colour.palet) + scale_fill_manual(values = colour.palet) + ggtitle(paste("BE", sample)) + theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + ylab("Number of mutations") + xlab("% BE cells") + xlim(0,2.1)
BE.only
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only.pdf"), BE.only, width = 14, height = 5, useDingbats = FALSE)

BE.clonal<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = as.factor(is.BE[data.plot$mutCount>0]), fill = as.factor(is.BE[data.plot$mutCount>0]))) + 
  geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + 
  geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity") +
  theme_minimal() + 
  scale_color_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE), values = c("FALSE" = "red", "TRUE" = "black")) + 
  scale_fill_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE),values = c("FALSE" = "red", "TRUE" = "black")) + 
  ggtitle(paste("BE", sample)) + 
  theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + 
  ylab("Number of mutations") + 
  xlab("% BE cells") + 
  xlim(0,2.1)
BE.clonal
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only_bw.pdf"), BE.clonal, width = 14, height = 5, useDingbats = FALSE)

i<-1
j<-3
# Plot the expression of these in BE and NE comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NE.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.6)
dev.off()

i<-2
j<-3
# Plot the expression of these in BE and NG comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NG.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.5)
dev.off()
```

# AHM0931

```{r AHM0931}
sample<-"AHM0931"
par(oma=c(3,3,0,0))
layout(matrix(1,1))

# ID of samples
samples.IDs<-samples[samples$Patient == sample & samples$Tissue %in% c("NE", "GC", "BE"),]
samples.IDs<-samples.IDs$Pool[match(samples.IDs$Tissue, c("NE", "GC", "BE"))]

# Read in data for DPCLust analysis of BE sample (by itself)
if (dir.exists(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/"))) {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
} else {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
}

# Identify clonal clusters
BE.clonal<- clustering$best.node.assignments %in% which(clustering$cluster.locations[,2]>0.8)

# Get tracking ID
tracking <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Store cluster information for BE sampels 
BE.cluster <-  clustering$best.node.assignments 

# Load data for multisamples DPClust analysis
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample, "_gsdata.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))

# Create colour palet that will be constant on all images
colour.palet<-c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 8, name = "Set2"))[1:max(clustering$cluster.locations[,1])]
names(colour.palet) <- clustering$cluster.locations[,1]

# Get tracking ID for the multisample DPClust
tracking2 <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Check if the mutations fulfils coverage test
cov.test <- rowAlls(dataset$WTCount+dataset$mutCount > z.cutoff)

# Check if the mutation is supported by enough reads
count.test <- rowAnys(dataset$mutCount > count.cutoff)

# Select data and build data printing dataframe
dataset$chromosome <- dataset$chromosome[cov.test & count.test,]
dataset$position <- dataset$position[cov.test & count.test,]
dataset$WTCount <- dataset$WTCount[cov.test & count.test,]
dataset$mutCount <- dataset$mutCount[cov.test & count.test,]
dataset$subclonal.fraction <- dataset$subclonal.fraction[cov.test & count.test,]
clustering$best.node.assignments <- clustering$best.node.assignments[cov.test & count.test]

BE.clonal <- BE.clonal[tracking %in% tracking2][cov.test & count.test]
BE.cluster <- BE.cluster[tracking %in% tracking2][cov.test & count.test]
# BE.clonal<-BE.clonal[cov.test & count.test]
# BE.clonal<- dataset$subclonal.fraction[,3]>0.5 

# Get vaf data
vaf.data <- dataset$mutCount/(dataset$mutCount+dataset$WTCount)


data.plot<-data.frame( "chr" = dataset$chromosome[ ,1 , drop = FALSE],
                       "position" = dataset$position[ ,1 , drop = FALSE],
                       "WTCount" = as.numeric(dataset$WTCount[ ,3 , drop = FALSE]),
                       "mutCount" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]),
                       "vaf" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]/(dataset$mutCount[ ,3 , drop = FALSE]+dataset$WTCount[ ,3 , drop = FALSE])),
                       "subfrac" = as.numeric(dataset$subclonal.fraction[ ,3 , drop = FALSE]),
                       "Cluster" = factor(BE.cluster)
)

rownames(data.plot)<-paste0("chr", data.plot$chr,":",data.plot$position)


# Check if mutations is prsent in all samples
is.all<-rowAlls(dataset$mutCount > count.cutoff)
# Check if mutations is present in normal samples
is.both<-rowAlls(dataset$mutCount[,1:2] > count.cutoff)

# Identify the mutations that are clonal in BE and approproprioate number of reads supporting the mutations and are missing in the normal smaples
is.BE<-data.plot$mutCount >= count.cutoff & BE.clonal & !is.both & data.plot$vaf > 0.15

# Plot only data for the BE samples from 1 samples DPClust

BE.only<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = Cluster, fill = Cluster)) + geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity")+ theme_minimal()+scale_color_manual(values = colour.palet) + scale_fill_manual(values = colour.palet) + ggtitle(paste("BE", sample)) + theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + ylab("Number of mutations") + xlab("% BE cells") + xlim(0,2.1)
BE.only
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only.pdf"), BE.only, width = 14, height = 5, useDingbats = FALSE)

BE.clonal<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = as.factor(is.BE[data.plot$mutCount>0]), fill = as.factor(is.BE[data.plot$mutCount>0]))) + 
  geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + 
  geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity") +
  theme_minimal() + 
  scale_color_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE), values = c("FALSE" = "red", "TRUE" = "black")) + 
  scale_fill_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE),values = c("FALSE" = "red", "TRUE" = "black")) + 
  ggtitle(paste("BE", sample)) + 
  theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + 
  ylab("Number of mutations") + 
  xlab("% BE cells") + 
  xlim(0,2.1)
BE.clonal
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only_bw.pdf"), BE.clonal, width = 14, height = 5, useDingbats = FALSE)

i<-1
j<-3
# Plot the expression of these in BE and NE comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NE.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.6)
dev.off()

i<-2
j<-3
# Plot the expression of these in BE and NG comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NG.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.5)
dev.off()
```

# AHM1218

```{r AHM1218}
sample<-"AHM1218"
par(oma=c(3,3,0,0))
layout(matrix(1,1))

# ID of samples
samples.IDs<-samples[samples$Patient == sample & samples$Tissue %in% c("NE", "GC", "BE"),]
samples.IDs<-samples.IDs$Pool[match(samples.IDs$Tissue, c("NE", "GC", "BE"))]

# Read in data for DPCLust analysis of BE sample (by itself)
if (dir.exists(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/"))) {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"_refit/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
} else {
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
  load(paste0(data.location, "/../DPClust_BE/",  "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))
}

# Identify clonal clusters
BE.clonal<- clustering$best.node.assignments %in% which(clustering$cluster.locations[,2]>0.8)

# Get tracking ID
tracking <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Store cluster information for BE sampels 
BE.cluster <-  clustering$best.node.assignments 

# Load data for multisamples DPClust analysis
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample,"_2000iters_1000burnin_bestConsensusResults.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/", sample, "_gsdata.RData"))
load(paste0(data.location, "/",sample,"/", "dpclust","/",sample, "_DPoutput_2000iters_1000burnin_seed123/","dataset.RData"))

# Create colour palet that will be constant on all images
colour.palet<-c(brewer.pal(n = 9, name = "Set1"), brewer.pal(n = 8, name = "Set2"))[1:max(clustering$cluster.locations[,1])]
names(colour.palet) <- clustering$cluster.locations[,1]

# Get tracking ID for the multisample DPClust
tracking2 <- paste(dataset$chromosome[,1], dataset$position[,1], sep = "_")

# Check if the mutations fulfils coverage test
cov.test <- rowAlls(dataset$WTCount+dataset$mutCount > z.cutoff)

# Check if the mutation is supported by enough reads
count.test <- rowAnys(dataset$mutCount > count.cutoff)

# Select data and build data printing dataframe
dataset$chromosome <- dataset$chromosome[cov.test & count.test,]
dataset$position <- dataset$position[cov.test & count.test,]
dataset$WTCount <- dataset$WTCount[cov.test & count.test,]
dataset$mutCount <- dataset$mutCount[cov.test & count.test,]
dataset$subclonal.fraction <- dataset$subclonal.fraction[cov.test & count.test,]
clustering$best.node.assignments <- clustering$best.node.assignments[cov.test & count.test]

BE.clonal <- BE.clonal[tracking %in% tracking2][cov.test & count.test]
BE.cluster <- BE.cluster[tracking %in% tracking2][cov.test & count.test]
# BE.clonal<-BE.clonal[cov.test & count.test]
# BE.clonal<- dataset$subclonal.fraction[,3]>0.5 

# Get vaf data
vaf.data <- dataset$mutCount/(dataset$mutCount+dataset$WTCount)


data.plot<-data.frame( "chr" = dataset$chromosome[ ,1 , drop = FALSE],
                       "position" = dataset$position[ ,1 , drop = FALSE],
                       "WTCount" = as.numeric(dataset$WTCount[ ,3 , drop = FALSE]),
                       "mutCount" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]),
                       "vaf" = as.numeric(dataset$mutCount[ ,3 , drop = FALSE]/(dataset$mutCount[ ,3 , drop = FALSE]+dataset$WTCount[ ,3 , drop = FALSE])),
                       "subfrac" = as.numeric(dataset$subclonal.fraction[ ,3 , drop = FALSE]),
                       "Cluster" = factor(BE.cluster)
)

rownames(data.plot)<-paste0("chr", data.plot$chr,":",data.plot$position)


# Check if mutations is prsent in all samples
is.all<-rowAlls(dataset$mutCount > count.cutoff)
# Check if mutations is present in normal samples
is.both<-rowAlls(dataset$mutCount[,1:2] > count.cutoff)

# Identify the mutations that are clonal in BE and approproprioate number of reads supporting the mutations and are missing in the normal smaples
is.BE<-data.plot$mutCount >= count.cutoff & BE.clonal & !is.both & data.plot$vaf > 0.15

# Plot only data for the BE samples from 1 samples DPClust

BE.only<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = Cluster, fill = Cluster)) + geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity")+ theme_minimal()+scale_color_manual(values = colour.palet) + scale_fill_manual(values = colour.palet) + ggtitle(paste("BE", sample)) + theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + ylab("Number of mutations") + xlab("% BE cells") + xlim(0,2.1)
BE.only
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only.pdf"), BE.only, width = 14, height = 5, useDingbats = FALSE)

BE.clonal<-ggplot(data.plot[data.plot$mutCount>0,], aes(x=subfrac, color = as.factor(is.BE[data.plot$mutCount>0]), fill = as.factor(is.BE[data.plot$mutCount>0]))) + 
  geom_histogram(binwidth = 0.01, alpha = 0.5, position = "identity")  + 
  geom_freqpoly(binwidth = 0.01, alpha = 1, position = "identity") +
  theme_minimal() + 
  scale_color_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE), values = c("FALSE" = "red", "TRUE" = "black")) + 
  scale_fill_manual(name = "Mutation type", labels = c("Subclonal", "Clonal"), guide = guide_legend(reverse=TRUE),values = c("FALSE" = "red", "TRUE" = "black")) + 
  ggtitle(paste("BE", sample)) + 
  theme(legend.position = c(.89, .8), legend.background = element_rect(fill="white", size=0.1, linetype="solid", colour ="black")) + 
  ylab("Number of mutations") + 
  xlab("% BE cells") + 
  xlim(0,2.1)
BE.clonal
ggsave(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/", sample,"_BE_only_bw.pdf"), BE.clonal, width = 14, height = 5, useDingbats = FALSE)

i<-1
j<-3
# Plot the expression of these in BE and NE comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NE.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.6)
dev.off()

i<-2
j<-3
# Plot the expression of these in BE and NG comparison
pdf(paste0("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Figure_3/",sample,"_BE_NG.pdf"), width = 5, height = 5, useDingbats = FALSE)
par(oma=c(3,3,0,0))
layout(matrix(1,1))
scatterhist(x = dataset$subclonal.fraction[is.BE,i], y = dataset$subclonal.fraction[is.BE,j], xhist = dataset$subclonal.fraction[,i], yhist = dataset$subclonal.fraction[,j], plot_mutations_colour = "black", max.plotted.value = c(4.2,4.2), xlab = paste("%",sample.names[i],"cells"), ylab = paste("%",sample.names[j],"cells"), main = sample, cutoff = 0.5)
dev.off()
```

# End Matters

Session Information

```{r End}
sessionInfo()
```






