---
title: "Figure S10: Entropy measures in all tissues"
author: "Karol Nowicki-Osuch, based on Nils Eling's code"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: paper
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we compute the entropy per cell for duodenum and normal oesophagus cells as a control for this measure to detect stem-cell-like phenotypes.

# Read in the data

```{r libraries, message=FALSE}
library(Rtsne)
library(viridis)
source("../../Analysis/Functions/auxiliary.R")

sce <- readRDS("~/Dropbox/Postdoc/2019-12-29_BE2020/All_corrected_sce_filtered.rds")

sce <- sce[,sce$include]
```


# Entropy in BE samples

```{r}
# Select BE cells
cur_sce <- sce[,sce$Tissue == "BE"]

# Only genes that are expressed
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]

# Normalization across all cells
cur_sce <- computeSumFactors(cur_sce, clusters=paste(cur_sce$cell_type_secondary))
cur_sce <- logNormCounts(cur_sce, log = FALSE)

cur_counts <- as.matrix(normcounts(cur_sce))

# Calculate entropy
probs   <- t(t(cur_counts)/colSums(cur_counts))
logprobs <- log(probs)
logprobs[logprobs == -Inf] <- 0
logprobs.1 <- probs*logprobs
entropy <- -colSums(probs*logprobs)

# Entropy is normalized based on the number of genes
entropy <- entropy/log(nrow(cur_counts))

sce.list <- split.sce(cur_sce, unique(cur_sce$Sample), colData.name = "Sample")
# Order sce object by size
sce.list <- sce.list[order(unlist(lapply(sce.list, ncol)), decreasing = TRUE)]

cur_sce <- do.call("cbind", sce.list)
corrected <- batch.correction(sce.list)

# Compute tSNE
set.seed(12345)
tsne <- Rtsne(t(corrected), pca = FALSE, perplexity = 100)

# Create colour vector
colour_vector <- vector(length = length(unique(cur_sce$cell_type_secondary)))
names(colour_vector) <- unique(cur_sce$cell_type_secondary)
colour_vector["Immune_T-cells"] <- "grey20"
colour_vector["Immune_B-cells"] <- "grey30"
colour_vector["Immune_Macrophages"] <- "grey40"
colour_vector["Stromal_CALD1_cells"] <- "grey60"
colour_vector["Stromal_GNG11_cells"] <- "grey70"

colour_vector["Columnar_Undifferentiated"] <- "white"
colour_vector["Columnar_Undifferentiated_Dividing"] <- colorRampPalette(c("white", "#00A087FF"))(10)[2]
colour_vector["Columnar_Intermediate"] <- colorRampPalette(c("white", "#00A087FF"))(10)[4]
colour_vector["Columnar_differentiated"] <- colorRampPalette(c("white", "#00A087FF"))(10)[6]
colour_vector["Endocrine_NEUROG3"] <- colorRampPalette(c("white", "dark green"))(10)[5]
colour_vector["Goblet"] <- colorRampPalette(c("white", "dark green"))(10)[10]

tsne.BE <- ggplot(data.frame(tSNE1 = tsne$Y[,1],
                             tSNE2 = tsne$Y[,2],
                             cell_type = cur_sce$cell_type_secondary)) + 
  geom_point(aes(tSNE1, tSNE2), colour = "black", size = 2) +
  geom_point(aes(tSNE1, tSNE2, colour = cell_type)) +
  scale_color_manual(values = colour_vector) + theme_minimal()
tsne.BE
# Colour by entropy
tsne.BE.entropy <- ggplot(data.frame(tSNE1 = tsne$Y[,1],
                                     tSNE2 = tsne$Y[,2],
                                     entropy = entropy)) + 
  geom_point(aes(tSNE1, tSNE2), colour = "black", size = 2) + 
  geom_point(aes(tSNE1, tSNE2, colour = entropy)) +
  scale_color_gradientn(colours = magma(100)) + theme_minimal()
tsne.BE.entropy

for.boxplot<-data.frame(cells = cur_sce$cell_type_secondary,
                        entropy = entropy)
for.boxplot<-for.boxplot[for.boxplot$cells %in% c("Columnar_Undifferentiated", "Columnar_Undifferentiated_Dividing", "Columnar_Intermediate", "Columnar_differentiated", "Endocrine_NEUROG3", "Goblet"),]
for.boxplot$cells<-factor(for.boxplot$cells, levels =c("Columnar_Undifferentiated", "Columnar_Undifferentiated_Dividing", "Columnar_Intermediate", "Columnar_differentiated", "Endocrine_NEUROG3", "Goblet") )

entropy.boxplot<-ggplot(for.boxplot) + 
  # geom_violin(aes(clusters, gene, fill = symbol), scale = "width") + facet_wrap(. ~ tissue)+ theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
  geom_boxplot(aes(cells, entropy)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

for.boxplot<-data.frame(cells = cur_sce$cell_type_secondary,
                        OLFM4 = log2(normcounts(cur_sce)[rowData(cur_sce)$Symbol == "OLFM4",] + 1))
for.boxplot<-for.boxplot[for.boxplot$cells %in% c("Columnar_Undifferentiated", "Columnar_Undifferentiated_Dividing", "Columnar_Intermediate", "Columnar_differentiated", "Endocrine_NEUROG3", "Goblet"),]
for.boxplot$cells<-factor(for.boxplot$cells, levels =c("Columnar_Undifferentiated", "Columnar_Undifferentiated_Dividing", "Columnar_Intermediate", "Columnar_differentiated", "Endocrine_NEUROG3", "Goblet") )

OLFM4.boxplot<-ggplot(for.boxplot) + 
  # geom_violin(aes(clusters, gene, fill = symbol), scale = "width") + facet_wrap(. ~ tissue)+ theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
  geom_boxplot(aes(cells, OLFM4)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))


# Visualize OLFM4
tsne.BE.OLFM4 <- ggplot(data.frame(tSNE1 = tsne$Y[,1],
                                   tSNE2 = tsne$Y[,2],
                                   OLFM4 = log2(normcounts(cur_sce)[rowData(cur_sce)$Symbol == "OLFM4",] + 1))) + 
  geom_point(aes(tSNE1, tSNE2), colour = "black", size = 2) + 
  geom_point(aes(tSNE1, tSNE2, colour = OLFM4)) +
  scale_color_viridis() + theme_minimal()
tsne.BE.OLFM4
ggsave("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Rebuttal/BE_entropy.pdf", entropy.boxplot, width = 15, height = 7, useDingbats = FALSE)
ggsave("~/Dropbox/Postdoc/2019-12-29_BE2020/Figures/Rebuttal/BE_OLFM4.pdf", OLFM4.boxplot, width = 15, height = 7, useDingbats = FALSE)

```

